// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"fmt"

	"github.com/gofiber/fiber/v3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// CreateMealRequest defines model for CreateMealRequest.
type CreateMealRequest struct {
	Calories int    `json:"calories"`
	Label    string `json:"label"`
}

// CreateMealResponse defines model for CreateMealResponse.
type CreateMealResponse struct {
	Meal Meal `json:"meal"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message string `json:"message"`
}

// GetMealResponse defines model for GetMealResponse.
type GetMealResponse struct {
	Meal Meal `json:"meal"`
}

// ListMealsResponse defines model for ListMealsResponse.
type ListMealsResponse struct {
	Meals []Meal `json:"meals"`
}

// Meal defines model for Meal.
type Meal struct {
	Calories int                `json:"calories"`
	Id       openapi_types.UUID `json:"id"`
	Label    string             `json:"label"`
}

// CreateMealJSONRequestBody defines body for CreateMeal for application/json ContentType.
type CreateMealJSONRequestBody = CreateMealRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListMeals List all meals
	// (GET /meals)
	ListMeals(c fiber.Ctx) error
	// CreateMeal Create a meal
	// (POST /meals)
	CreateMeal(c fiber.Ctx) error
	// GetMeal Fetch one meal
	// (GET /meals/{mealId})
	GetMeal(c fiber.Ctx, mealId openapi_types.UUID) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []HandlerMiddlewareFunc
}

type MiddlewareFunc fiber.Handler
type HandlerMiddlewareFunc func(c fiber.Ctx, next fiber.Handler) error

// ListMeals operation middleware
func (siw *ServerInterfaceWrapper) ListMeals(c fiber.Ctx) error {

	handler := func(c fiber.Ctx) error {
		return siw.Handler.ListMeals(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// CreateMeal operation middleware
func (siw *ServerInterfaceWrapper) CreateMeal(c fiber.Ctx) error {

	handler := func(c fiber.Ctx) error {
		return siw.Handler.CreateMeal(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// GetMeal operation middleware
func (siw *ServerInterfaceWrapper) GetMeal(c fiber.Ctx) error {

	var err error
	_ = err

	// ------------- Path parameter "mealId" -------------
	var mealId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "mealId", c.Params("mealId"), &mealId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter mealId: %w", err).Error())
	}

	handler := func(c fiber.Ctx) error {
		return siw.Handler.GetMeal(c, mealId)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL            string
	Middlewares        []MiddlewareFunc
	HandlerMiddlewares []HandlerMiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.HandlerMiddlewares,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Get(options.BaseURL+"/meals", wrapper.ListMeals)

	router.Post(options.BaseURL+"/meals", wrapper.CreateMeal)

	router.Get(options.BaseURL+"/meals/:mealId", wrapper.GetMeal)

}
