// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: calendar_days.sql

package db

import (
	"context"
	"database/sql"
)

const assignCalendarDay = `-- name: AssignCalendarDay :one
INSERT INTO calendar_days (date, day_plan_id, created_at, updated_at)
VALUES (?, ?, ?, ?)
ON CONFLICT (date) DO UPDATE
SET day_plan_id = excluded.day_plan_id, updated_at = excluded.updated_at, deleted_at = NULL
RETURNING date, day_plan_id, created_at, updated_at, deleted_at
`

type AssignCalendarDayParams struct {
	Date      string
	DayPlanID string
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) AssignCalendarDay(ctx context.Context, arg AssignCalendarDayParams) (CalendarDay, error) {
	row := q.db.QueryRowContext(ctx, assignCalendarDay,
		arg.Date,
		arg.DayPlanID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CalendarDay
	err := row.Scan(
		&i.Date,
		&i.DayPlanID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCalendarDay = `-- name: GetCalendarDay :one
SELECT date, day_plan_id, created_at, updated_at, deleted_at FROM calendar_days WHERE date = ? AND deleted_at IS NULL
`

func (q *Queries) GetCalendarDay(ctx context.Context, date string) (CalendarDay, error) {
	row := q.db.QueryRowContext(ctx, getCalendarDay, date)
	var i CalendarDay
	err := row.Scan(
		&i.Date,
		&i.DayPlanID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCalendarDays = `-- name: ListCalendarDays :many
SELECT date, day_plan_id, created_at, updated_at, deleted_at FROM calendar_days WHERE date >= ? AND date <= ? AND deleted_at IS NULL ORDER BY date
`

type ListCalendarDaysParams struct {
	Date   string
	Date_2 string
}

func (q *Queries) ListCalendarDays(ctx context.Context, arg ListCalendarDaysParams) ([]CalendarDay, error) {
	rows, err := q.db.QueryContext(ctx, listCalendarDays, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CalendarDay
	for rows.Next() {
		var i CalendarDay
		if err := rows.Scan(
			&i.Date,
			&i.DayPlanID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCalendarDay = `-- name: SoftDeleteCalendarDay :execrows
UPDATE calendar_days SET deleted_at = ?, updated_at = ? WHERE date = ? AND deleted_at IS NULL
`

type SoftDeleteCalendarDayParams struct {
	DeletedAt sql.NullString
	UpdatedAt string
	Date      string
}

func (q *Queries) SoftDeleteCalendarDay(ctx context.Context, arg SoftDeleteCalendarDayParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteCalendarDay, arg.DeletedAt, arg.UpdatedAt, arg.Date)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
