// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: day_plans.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const createDayPlan = `-- name: CreateDayPlan :one
INSERT INTO day_plans (id, label, created_at, updated_at) VALUES (?, ?, ?, ?) RETURNING id, label, created_at, updated_at, deleted_at
`

type CreateDayPlanParams struct {
	ID        string
	Label     string
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) CreateDayPlan(ctx context.Context, arg CreateDayPlanParams) (DayPlan, error) {
	row := q.db.QueryRowContext(ctx, createDayPlan,
		arg.ID,
		arg.Label,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i DayPlan
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createDayPlanMeal = `-- name: CreateDayPlanMeal :exec
INSERT INTO day_plan_meals (id, day_plan_id, meal_id, position, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateDayPlanMealParams struct {
	ID        string
	DayPlanID string
	MealID    string
	Position  int64
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) CreateDayPlanMeal(ctx context.Context, arg CreateDayPlanMealParams) error {
	_, err := q.db.ExecContext(ctx, createDayPlanMeal,
		arg.ID,
		arg.DayPlanID,
		arg.MealID,
		arg.Position,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getDayPlan = `-- name: GetDayPlan :one
SELECT id, label, created_at, updated_at, deleted_at FROM day_plans WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) GetDayPlan(ctx context.Context, id string) (DayPlan, error) {
	row := q.db.QueryRowContext(ctx, getDayPlan, id)
	var i DayPlan
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listDayPlanMealsByDayPlanIDs = `-- name: ListDayPlanMealsByDayPlanIDs :many
SELECT id, day_plan_id, meal_id, position, created_at, updated_at, deleted_at FROM day_plan_meals
WHERE day_plan_id IN (/*SLICE:day_plan_ids*/?) AND deleted_at IS NULL
ORDER BY day_plan_id, position
`

func (q *Queries) ListDayPlanMealsByDayPlanIDs(ctx context.Context, dayPlanIds []string) ([]DayPlanMeal, error) {
	query := listDayPlanMealsByDayPlanIDs
	var queryParams []interface{}
	if len(dayPlanIds) > 0 {
		for _, v := range dayPlanIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:day_plan_ids*/?", strings.Repeat(",?", len(dayPlanIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:day_plan_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DayPlanMeal
	for rows.Next() {
		var i DayPlanMeal
		if err := rows.Scan(
			&i.ID,
			&i.DayPlanID,
			&i.MealID,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDayPlans = `-- name: ListDayPlans :many
SELECT id, label, created_at, updated_at, deleted_at FROM day_plans WHERE deleted_at IS NULL ORDER BY label, id
`

func (q *Queries) ListDayPlans(ctx context.Context) ([]DayPlan, error) {
	rows, err := q.db.QueryContext(ctx, listDayPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DayPlan
	for rows.Next() {
		var i DayPlan
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDayPlansByIDs = `-- name: ListDayPlansByIDs :many
SELECT id, label, created_at, updated_at, deleted_at FROM day_plans WHERE id IN (/*SLICE:ids*/?) AND deleted_at IS NULL
`

func (q *Queries) ListDayPlansByIDs(ctx context.Context, ids []string) ([]DayPlan, error) {
	query := listDayPlansByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DayPlan
	for rows.Next() {
		var i DayPlan
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteDayPlan = `-- name: SoftDeleteDayPlan :execrows
UPDATE day_plans SET deleted_at = ?, updated_at = ? WHERE id = ? AND deleted_at IS NULL
`

type SoftDeleteDayPlanParams struct {
	DeletedAt sql.NullString
	UpdatedAt string
	ID        string
}

func (q *Queries) SoftDeleteDayPlan(ctx context.Context, arg SoftDeleteDayPlanParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteDayPlan, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const softDeleteDayPlanMeals = `-- name: SoftDeleteDayPlanMeals :exec
UPDATE day_plan_meals SET deleted_at = ?, updated_at = ? WHERE day_plan_id = ? AND deleted_at IS NULL
`

type SoftDeleteDayPlanMealsParams struct {
	DeletedAt sql.NullString
	UpdatedAt string
	DayPlanID string
}

func (q *Queries) SoftDeleteDayPlanMeals(ctx context.Context, arg SoftDeleteDayPlanMealsParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteDayPlanMeals, arg.DeletedAt, arg.UpdatedAt, arg.DayPlanID)
	return err
}

const updateDayPlan = `-- name: UpdateDayPlan :one
UPDATE day_plans SET label = ?, updated_at = ? WHERE id = ? AND deleted_at IS NULL RETURNING id, label, created_at, updated_at, deleted_at
`

type UpdateDayPlanParams struct {
	Label     string
	UpdatedAt string
	ID        string
}

func (q *Queries) UpdateDayPlan(ctx context.Context, arg UpdateDayPlanParams) (DayPlan, error) {
	row := q.db.QueryRowContext(ctx, updateDayPlan, arg.Label, arg.UpdatedAt, arg.ID)
	var i DayPlan
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
