// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: meals.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const createMeal = `-- name: CreateMeal :one
INSERT INTO meals (id, label, created_at, updated_at) VALUES (?, ?, ?, ?) RETURNING id, label, created_at, updated_at, deleted_at
`

type CreateMealParams struct {
	ID        string
	Label     string
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) CreateMeal(ctx context.Context, arg CreateMealParams) (Meal, error) {
	row := q.db.QueryRowContext(ctx, createMeal,
		arg.ID,
		arg.Label,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createMealServing = `-- name: CreateMealServing :exec
INSERT INTO meal_servings (id, meal_id, product_id, amount, position, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateMealServingParams struct {
	ID        string
	MealID    string
	ProductID string
	Amount    float64
	Position  int64
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) CreateMealServing(ctx context.Context, arg CreateMealServingParams) error {
	_, err := q.db.ExecContext(ctx, createMealServing,
		arg.ID,
		arg.MealID,
		arg.ProductID,
		arg.Amount,
		arg.Position,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getMeal = `-- name: GetMeal :one
SELECT id, label, created_at, updated_at, deleted_at FROM meals WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) GetMeal(ctx context.Context, id string) (Meal, error) {
	row := q.db.QueryRowContext(ctx, getMeal, id)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listMealServingsByMealIDs = `-- name: ListMealServingsByMealIDs :many
SELECT id, meal_id, product_id, amount, position, created_at, updated_at, deleted_at FROM meal_servings
WHERE meal_id IN (/*SLICE:meal_ids*/?) AND deleted_at IS NULL
ORDER BY meal_id, position
`

func (q *Queries) ListMealServingsByMealIDs(ctx context.Context, mealIds []string) ([]MealServing, error) {
	query := listMealServingsByMealIDs
	var queryParams []interface{}
	if len(mealIds) > 0 {
		for _, v := range mealIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:meal_ids*/?", strings.Repeat(",?", len(mealIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:meal_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MealServing
	for rows.Next() {
		var i MealServing
		if err := rows.Scan(
			&i.ID,
			&i.MealID,
			&i.ProductID,
			&i.Amount,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMeals = `-- name: ListMeals :many
SELECT id, label, created_at, updated_at, deleted_at FROM meals WHERE deleted_at IS NULL ORDER BY label, id
`

func (q *Queries) ListMeals(ctx context.Context) ([]Meal, error) {
	rows, err := q.db.QueryContext(ctx, listMeals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meal
	for rows.Next() {
		var i Meal
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealsByIDs = `-- name: ListMealsByIDs :many
SELECT id, label, created_at, updated_at, deleted_at FROM meals WHERE id IN (/*SLICE:ids*/?) AND deleted_at IS NULL
`

func (q *Queries) ListMealsByIDs(ctx context.Context, ids []string) ([]Meal, error) {
	query := listMealsByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meal
	for rows.Next() {
		var i Meal
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteMeal = `-- name: SoftDeleteMeal :execrows
UPDATE meals SET deleted_at = ?, updated_at = ? WHERE id = ? AND deleted_at IS NULL
`

type SoftDeleteMealParams struct {
	DeletedAt sql.NullString
	UpdatedAt string
	ID        string
}

func (q *Queries) SoftDeleteMeal(ctx context.Context, arg SoftDeleteMealParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteMeal, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const softDeleteMealServings = `-- name: SoftDeleteMealServings :exec
UPDATE meal_servings SET deleted_at = ?, updated_at = ? WHERE meal_id = ? AND deleted_at IS NULL
`

type SoftDeleteMealServingsParams struct {
	DeletedAt sql.NullString
	UpdatedAt string
	MealID    string
}

func (q *Queries) SoftDeleteMealServings(ctx context.Context, arg SoftDeleteMealServingsParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteMealServings, arg.DeletedAt, arg.UpdatedAt, arg.MealID)
	return err
}

const updateMeal = `-- name: UpdateMeal :one
UPDATE meals SET label = ?, updated_at = ? WHERE id = ? AND deleted_at IS NULL RETURNING id, label, created_at, updated_at, deleted_at
`

type UpdateMealParams struct {
	Label     string
	UpdatedAt string
	ID        string
}

func (q *Queries) UpdateMeal(ctx context.Context, arg UpdateMealParams) (Meal, error) {
	row := q.db.QueryRowContext(ctx, updateMeal, arg.Label, arg.UpdatedAt, arg.ID)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
