// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (id, name, unit, energy_kcal, fat_g, protein_g, carbohydrates_g, nutrients, source_code, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, unit, energy_kcal, fat_g, protein_g, carbohydrates_g, nutrients, source_code, created_at, updated_at, deleted_at
`

type CreateProductParams struct {
	ID             string
	Name           string
	Unit           string
	EnergyKcal     float64
	FatG           float64
	ProteinG       float64
	CarbohydratesG float64
	Nutrients      string
	SourceCode     sql.NullString
	CreatedAt      string
	UpdatedAt      string
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.ID,
		arg.Name,
		arg.Unit,
		arg.EnergyKcal,
		arg.FatG,
		arg.ProteinG,
		arg.CarbohydratesG,
		arg.Nutrients,
		arg.SourceCode,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Unit,
		&i.EnergyKcal,
		&i.FatG,
		&i.ProteinG,
		&i.CarbohydratesG,
		&i.Nutrients,
		&i.SourceCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT id, name, unit, energy_kcal, fat_g, protein_g, carbohydrates_g, nutrients, source_code, created_at, updated_at, deleted_at FROM products WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) GetProduct(ctx context.Context, id string) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Unit,
		&i.EnergyKcal,
		&i.FatG,
		&i.ProteinG,
		&i.CarbohydratesG,
		&i.Nutrients,
		&i.SourceCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, unit, energy_kcal, fat_g, protein_g, carbohydrates_g, nutrients, source_code, created_at, updated_at, deleted_at FROM products WHERE deleted_at IS NULL ORDER BY name, id
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Unit,
			&i.EnergyKcal,
			&i.FatG,
			&i.ProteinG,
			&i.CarbohydratesG,
			&i.Nutrients,
			&i.SourceCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByIDs = `-- name: ListProductsByIDs :many
SELECT id, name, unit, energy_kcal, fat_g, protein_g, carbohydrates_g, nutrients, source_code, created_at, updated_at, deleted_at FROM products WHERE id IN (/*SLICE:ids*/?) AND deleted_at IS NULL
`

func (q *Queries) ListProductsByIDs(ctx context.Context, ids []string) ([]Product, error) {
	query := listProductsByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Unit,
			&i.EnergyKcal,
			&i.FatG,
			&i.ProteinG,
			&i.CarbohydratesG,
			&i.Nutrients,
			&i.SourceCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProduct = `-- name: SoftDeleteProduct :execrows
UPDATE products SET deleted_at = ?, updated_at = ? WHERE id = ? AND deleted_at IS NULL
`

type SoftDeleteProductParams struct {
	DeletedAt sql.NullString
	UpdatedAt string
	ID        string
}

func (q *Queries) SoftDeleteProduct(ctx context.Context, arg SoftDeleteProductParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteProduct, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET name = ?, unit = ?, energy_kcal = ?, fat_g = ?, protein_g = ?, carbohydrates_g = ?, nutrients = ?, updated_at = ?
WHERE id = ? AND deleted_at IS NULL
RETURNING id, name, unit, energy_kcal, fat_g, protein_g, carbohydrates_g, nutrients, source_code, created_at, updated_at, deleted_at
`

type UpdateProductParams struct {
	Name           string
	Unit           string
	EnergyKcal     float64
	FatG           float64
	ProteinG       float64
	CarbohydratesG float64
	Nutrients      string
	UpdatedAt      string
	ID             string
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProduct,
		arg.Name,
		arg.Unit,
		arg.EnergyKcal,
		arg.FatG,
		arg.ProteinG,
		arg.CarbohydratesG,
		arg.Nutrients,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Unit,
		&i.EnergyKcal,
		&i.FatG,
		&i.ProteinG,
		&i.CarbohydratesG,
		&i.Nutrients,
		&i.SourceCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
