// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: targets.sql

package db

import (
	"context"
)

const getTargets = `-- name: GetTargets :one
SELECT id, energy_kcal, fat_g, protein_g, carbohydrates_g, created_at, updated_at, deleted_at FROM targets WHERE id = 1 AND deleted_at IS NULL
`

func (q *Queries) GetTargets(ctx context.Context) (Target, error) {
	row := q.db.QueryRowContext(ctx, getTargets)
	var i Target
	err := row.Scan(
		&i.ID,
		&i.EnergyKcal,
		&i.FatG,
		&i.ProteinG,
		&i.CarbohydratesG,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const setTargets = `-- name: SetTargets :one
INSERT INTO targets (id, energy_kcal, fat_g, protein_g, carbohydrates_g, created_at, updated_at)
VALUES (1, ?, ?, ?, ?, ?, ?)
ON CONFLICT (id) DO UPDATE
SET energy_kcal = excluded.energy_kcal, fat_g = excluded.fat_g, protein_g = excluded.protein_g,
    carbohydrates_g = excluded.carbohydrates_g, updated_at = excluded.updated_at, deleted_at = NULL
RETURNING id, energy_kcal, fat_g, protein_g, carbohydrates_g, created_at, updated_at, deleted_at
`

type SetTargetsParams struct {
	EnergyKcal     float64
	FatG           float64
	ProteinG       float64
	CarbohydratesG float64
	CreatedAt      string
	UpdatedAt      string
}

func (q *Queries) SetTargets(ctx context.Context, arg SetTargetsParams) (Target, error) {
	row := q.db.QueryRowContext(ctx, setTargets,
		arg.EnergyKcal,
		arg.FatG,
		arg.ProteinG,
		arg.CarbohydratesG,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Target
	err := row.Scan(
		&i.ID,
		&i.EnergyKcal,
		&i.FatG,
		&i.ProteinG,
		&i.CarbohydratesG,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
